config/routes.rb
Rails.application.routes.draw do
  get 'ideamachines/index'

  get 'ideamachines/create'

  get 'ideamachines/edit'

  get 'ideamachines/destroy'

  get 'ideamachines/show'

  get 'ideamachines/new'

  get 'ideamachines/update'

  get 'ideas/index'

  get 'ideas/create'

  get 'ideas/edit'

  get 'ideas/destroy'

  get 'ideas/show'

  get 'ideas/new'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  belongs_to :ideamachine
end

app/models/ideamachine.rb
class Ideamachine < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ideamachines_controller.rb
class IdeamachinesController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def new
  end

  def update
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
  end

  def create
  end

  def edit
  end

  def destroy
  end

  def show
  end

  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideamachines/create.html.erb
<h1>Ideamachines#create</h1>
<p>Find me in app/views/ideamachines/create.html.erb</p>

<h1>Ideas#create</h1>
<p>Find me in app/views/ideas/create.html.erb</p>

<%= simple_form_for(@ideamachine) do |f| %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/ideamachines/destroy.html.erb
<h1>Ideamachines#destroy</h1>
<p>Find me in app/views/ideamachines/destroy.html.erb</p>

app/views/ideamachines/edit.html.erb
<h1>Ideamachines#edit</h1>
<p>Find me in app/views/ideamachines/edit.html.erb</p>

app/views/ideamachines/index.html.erb
<h1>Ideamachines#index</h1>
<p>Find me in app/views/ideamachines/index.html.erb</p>

<%= @ideamachines.each do |ideamachine| %>

<div class="col-l-12 col-xs-12 col-sm-12">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path experience.photos[0].path if experience.photos.any? %>');">
    <div class="card-description">
      <h1><%= ideamachine.user.name %></h1>
    </div>
    <div class="card-category">
      <h3><%= ideamachine.price %></h3>
    </div>
  </div>
</div>

<% end %>

app/views/ideamachines/new.html.erb
<h1>Ideamachines#new</h1>
<p>Find me in app/views/ideamachines/new.html.erb</p>

app/views/ideamachines/show.html.erb
<div class="container">
  <h1>Ideamachines#show</h1>
  <p>Find me in app/views/ideamachines/show.html.erb</p>

  <%= simple_form_for Idea.new, url: ideas_create_path do |f| %>
      <%= f.input :content %>
      <!-- <h1> You will pay <%#= @ideamachine.price %> to submit</h1> -->
      <%= f.button :submit %>
  <% end %>
</div>

app/views/ideamachines/update.html.erb
<h1>Ideamachines#update</h1>
<p>Find me in app/views/ideamachines/update.html.erb</p>

app/views/ideas/create.html.erb
<h1>Ideas#create</h1>
<p>Find me in app/views/ideas/create.html.erb</p>

<%= simple_form_for(@idea) do |f| %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

app/views/ideas/destroy.html.erb
<h1>Ideas#destroy</h1>
<p>Find me in app/views/ideas/destroy.html.erb</p>

app/views/ideas/edit.html.erb
<h1>Ideas#edit</h1>
<p>Find me in app/views/ideas/edit.html.erb</p>

app/views/ideas/index.html.erb
<h1>Ideas#index</h1>
<p>Find me in app/views/ideas/index.html.erb</p>

app/views/ideas/new.html.erb
<h1>Ideas#new</h1>
<p>Find me in app/views/ideas/new.html.erb</p>

app/views/ideas/show.html.erb
<h1>Ideas#show</h1>
<p>Find me in app/views/ideas/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>

<div class="container">
  <h1>Welcome to the IdeaMachine mofos</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</div>

<ul>
  <li>
      <%= link_to 'ideas/create', ideas_create_path %>
  </li>
  <li>  <%= link_to 'ideamachines/create', ideamachines_create_path %>
  </li>
</ul>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

</div>